- build: 1.1.1/centos/7
  image:
    - mesoscloud/marathon:1.1.1-centos-7
    - mesoscloud/marathon:1.1.1-centos
    - mesoscloud/marathon:1.1.1
    - mesoscloud/marathon:latest

- build: 1.1.1/ubuntu/15.04
  image:
    - mesoscloud/marathon:1.1.1-ubuntu-15.04
    - mesoscloud/marathon:1.1.1-ubuntu


- tests:
    - cmd: marathon -h 2> /dev/null | grep 'USAGE.*marathon'

    - cmd: test -z "$MARATHON_MESOS_AUTHENTICATION_SECRET_FILE"

    - cmd: test -n "$MARATHON_MESOS_AUTHENTICATION_SECRET_FILE"
      env:
        - SECRET=password
