- build: 0.13.0/centos/7
  image:
    - mesoscloud/marathon:0.13.0-centos-7
    - mesoscloud/marathon:0.13.0-centos
    - mesoscloud/marathon:0.13.0
    - mesoscloud/marathon:latest

- build: 0.13.0/ubuntu/15.04
  image:
    - mesoscloud/marathon:0.13.0-ubuntu-15.04
    - mesoscloud/marathon:0.13.0-ubuntu

- build: 0.11.1/centos/7
  image:
    - mesoscloud/marathon:0.11.1-centos-7
    - mesoscloud/marathon:0.11.1-centos
    - mesoscloud/marathon:0.11.1

- build: 0.11.1/ubuntu/15.04
  image:
    - mesoscloud/marathon:0.11.1-ubuntu-15.04
    - mesoscloud/marathon:0.11.1-ubuntu

- build: 0.11.0/centos/7
  image:
    - mesoscloud/marathon:0.11.0-centos-7
    - mesoscloud/marathon:0.11.0-centos
    - mesoscloud/marathon:0.11.0

- build: 0.11.0/ubuntu/15.04
  image:
    - mesoscloud/marathon:0.11.0-ubuntu-15.04
    - mesoscloud/marathon:0.11.0-ubuntu

- build: 0.10.1/centos/7
  image:
    - mesoscloud/marathon:0.10.1-centos-7
    - mesoscloud/marathon:0.10.1-centos
    - mesoscloud/marathon:0.10.1

- build: 0.10.1/ubuntu/14.04
  image:
    - mesoscloud/marathon:0.10.1-ubuntu-14.04
    - mesoscloud/marathon:0.10.1-ubuntu

- build: 0.10.0/centos/7
  image:
    - mesoscloud/marathon:0.10.0-centos-7
    - mesoscloud/marathon:0.10.0-centos
    - mesoscloud/marathon:0.10.0

- build: 0.10.0/ubuntu/14.04
  image:
    - mesoscloud/marathon:0.10.0-ubuntu-14.04
    - mesoscloud/marathon:0.10.0-ubuntu

- build: 0.9.1/centos/7
  image:
    - mesoscloud/marathon:0.9.1-centos-7
    - mesoscloud/marathon:0.9.1-centos
    - mesoscloud/marathon:0.9.1

- build: 0.9.1/ubuntu/14.04
  image:
    - mesoscloud/marathon:0.9.1-ubuntu-14.04
    - mesoscloud/marathon:0.9.1-ubuntu


- tests:
    - cmd: marathon -h 2> /dev/null | grep 'USAGE.*marathon'

    - cmd: test -z "$MARATHON_MESOS_AUTHENTICATION_SECRET_FILE"

    - cmd: test -n "$MARATHON_MESOS_AUTHENTICATION_SECRET_FILE"
      env:
        - SECRET=password
